"""
Django settings for faidChatbot project.
Optimized for Vercel Deployment.
"""

from pathlib import Path
import os
import sys
from decouple import config
import dj_database_url
from dotenv import load_dotenv


load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY', default='django-insecure-h_q3wl7=flr(2pf&&x)qn(4#q69)yx3@gwf&ltag33p8ig9fp0')

# SECURITY WARNING: don't run with debug turned on in production!
# Toggles DEBUG to True if DJANGO_DEBUG environment variable is explicitly set to 'True'
if os.environ.get('DJANGO_DEBUG') == 'True':
    DEBUG = True
else:
    DEBUG = 'VERCEL' not in os.environ

ALLOWED_HOSTS = [
    '127.0.0.1',
    'localhost',
    'laborious-brande-relievedly.ngrok-free.dev',
    '.vercel.app',  # Allows any sub-domain generated by Vercel
    '*',            # Safely allows custom routing permutations for initial connection debugs
]

CSRF_TRUSTED_ORIGINS = [
    "https://faid-chatbot-3l2i.vercel.app",
    "https://faidChatbot.vercel.app",
]
# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
    'profiles.apps.ProfilesConfig',
    'authentication',
    'chat',
    'history',
    'homepage',
    'ussd',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'faidChatbot.settings.DynamicSiteMiddleware',
    'allauth.account.middleware.AccountMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'faidChatbot.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                "profiles.context_processor.user_profile",
            ],
        },
    },
]

WSGI_APPLICATION = 'faidChatbot.wsgi.application'

# Database Setup Configuration
# Fixes Vercel's build-stage pre-compilation backend loading exception
DATABASE_URL = os.environ.get('DATABASE_URL') or config('DATABASE_URL', default=None)

# True if currently building or running inside Vercel's platform
IS_VERCEL = os.environ.get('VERCEL') == '1'

if IS_VERCEL and not DATABASE_URL:
    # Safe fallback using the CORRECT sqlite3 engine path for the build step
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': ':memory:',  # Faster and cleaner for serverless builds
        }
    }
elif DATABASE_URL:
    DATABASES = {
        'default': dj_database_url.parse(
            DATABASE_URL,
            conn_max_age=0,  # Set to 0 to prevent connection pooling exhaustion in Serverless environments
            ssl_require=True
        )
    }
else:
    # Local development default configuration
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }

# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {'min_length': 8}
    },
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
    {'NAME': 'authentication.validators.StrongPasswordValidator'},
]

# Internationalization
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

# Static & Media files configuration for Vercel
STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

GEMINI_API_KEY = config('GEMINI_API_KEY', default='')
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

# Set a static fallback so Django compiles cleanly
SITE_ID = 1

# Add this custom middleware class directly inside your settings.py file
class DynamicSiteMiddleware:
    def __init__(self, get_response):
        self.get_response = get_response

    def __call__(self, request):
        from django.contrib.sites.models import Site
        from django.conf import settings
        try:
            # Match the site by looking at your current browser URL host domain
            current_host = request.get_host().split(':')[0]
            site = Site.objects.get(domain__iexact=current_host)
            settings.SITE_ID = site.id
        except Exception:
            # Fallback to the very first record if things aren't configured yet
            first_site = Site.objects.first()
            if first_site:
                settings.SITE_ID = first_site.id
                
        return self.get_response(request)

SOCIALACCOUNT_STORE_TOKENS = False

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]

SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'APP': {
            'client_id': config('GOOGLE_CLIENT_ID', default=''),
            'secret': config('GOOGLE_SECRET_KEY', default=''),
            'key': ''
        },
        'SCOPE': ['profile', 'email'],
        'AUTH_PARAMS': {
            'access_type': 'online',
            'prompt': 'select_account',  
        },
        'OAUTH_PKCE_ENABLED': True,
    }
}


SOCIALACCOUNT_LOGIN_ON_GET = True
SOCIALACCOUNT_AUTO_SIGNUP = True
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_USERNAME_REQUIRED = False
ACCOUNT_AUTHENTICATION_METHOD = 'email'


LOGIN_REDIRECT_URL = '/chat/'
LOGOUT_REDIRECT_URL = '/'
ACCOUNT_LOGOUT_ON_GET = True


# Safely handles database sync only during an active web request block
if IS_VERCEL and DATABASE_URL:
    # Only run if explicitly handling a real web process, preventing inspection tool noise
    if any(cmd in sys.argv for cmd in ['runserver', 'wsgi', 'asgi']) or 'vercel_wsgi' in sys.modules:
        try:
            from django.core.management import call_command
            call_command('migrate', interactive=False)
        except Exception:
            pass  # Suppressed prints to keep Vercel JSON compilation clean

        try:
            from django.contrib.sites.models import Site
            site, created = Site.objects.get_or_create(id=1)
            if created or site.domain == 'example.com':
                site.domain = 'faid-chatbot.vercel.app'
                site.name = 'Faid Chatbot'
                site.save()
        except Exception:
            pass  # Suppressed prints to keep Vercel JSON compilation clean


if IS_VERCEL and DATABASE_URL:
    # Only run when serving a real web request to prevent setup build noise
    if any(cmd in sys.argv for cmd in ['runserver', 'wsgi', 'asgi']) or 'vercel_wsgi' in sys.modules:
        try:
            import django
            django.setup()
            from django.contrib.sites.models import Site
            
            # This forces Django to create Site ID 1 if it's missing in your Supabase DB
            site, created = Site.objects.get_or_create(id=1)
            if created or site.domain == 'example.com':
                site.domain = 'faid-chatbot.vercel.app'  # Put your actual Vercel domain here
                site.name = 'Faid Chatbot'
                site.save()
        except Exception:
            pass