# Generated by Django 6.0.5 on 2026-06-18 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chathistory',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
